### ISSUE TITLE
Buttoninteraction is not transparent

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1050] opened 2018-11-13 07:07 UTC
**Describe the bug**
Buttonhandling is not consistent. Reported by OBK

**To Reproduce**
1. tbd

**Expected behavior**
A clear behaviour of the buttons. 
* close via x-Button in dialog should deactivate the button (except featureInfo - when deactivate on close=false)
* close-Button at bottom of dialog should deactivate the button 
* click on button in toolbar should deactivate the button
* if button is in a group: click on another button of the group should deactivate the button

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7

**Comment by werrolf** [comment] 2019-02-13 09:14
As we've discussed before, it's not the buttons that are inconsistent, it's the elements that are inconsistent. The external control API to invoke on an Element to get it to cooperate is highly variable. This necessitates deep knowledge, or glances into the code, to correctly configure a controlling button.

Github won't let me attach the spreadsheet here unfortunately, but I've done some digging.

There's one big family that supports `open` and `close`. Another smaller family that supports `activate` and `deactivate` (Redlining, Ruler _open_ _a_ _popup_ on activate). Some support both interchangeably (Redlining, Coordinates Utility). One (POI) only supports the weird pair of `activate` and `close`.
Not all of these are intended to be controlled by an outside button, but they are capable. E.g. AboutDialog and GpsPosition both act quasi as their own button, but their APIs also work fine for Button control.

Some Elements only ever work in a sidepane (Digitizer), while others only ever work in a popup (POI, SuggestMap and friends).

It's these inconsistencies that need to be tackled before we can have straightforward button configurations.

**Comment by werrolf** [comment] 2019-02-13 09:31
Also, there is really no way to tell for a button whether or not its controlled Element is active or not. Elements have multiple, inconsistent ways to "open automatically", so not even the initial state for the button is known.

Also see #549.

**Comment by rschwammborn** [comment] 2019-04-15 10:16
In Mapbender 3.0.8, buttons in the default toolbar perform as described under "Expected Behaviour".
Closing this issue for the moment, feel free to reopen if new button complexities appear.

**Closed by rschwammborn** 2019-04-15 10:16 UTC
