### ISSUE TITLE
Wrong results with line and area rulers starting SRS 3857

### ISSUE THREAD

**Issue by JudyBo** [mapbender/mapbender#1309] opened 2021-02-17 14:06 UTC
Hi, I am using Mapbender 3 as a global scale app and therefore the starting SRS is EPSG 3857. Both the line and area rulers give wrong results. I think it is because the SRS is not really metric. But I cannot start in e.g. a UTM extent because of the global extent that I need. How can I fix this?

Thanks

**Comment by thzanger** [comment] 2021-02-22 08:35
Dear @JudyBo, 
as all projected coordinate systems, EPSG3857 comes with its strengths and weaknesses. In your case, measurements become increasingly inaccurate away from the equator. Hence, it is not suitable for distance measurements. I recommend two options: 1. Use a local UTM zone to calculate distances for a specific region. 2. Convert your coordinates into lat and long. Now you can calculate the distance between different points on the sphere using e.g. the haversine formula. 
Since this problem is not a bug of Mapbender, but results from the inherent characteristics of your SRS, I will close this issue.
Regards

**Closed by thzanger** 2021-02-22 08:35 UTC
