### ISSUE TITLE
[Backend][Dimensions handler]Dimensions handler configuration window doesn't offer all possibilities on first startup

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#1164] opened 2019-05-13 08:50 UTC
**Describe the bug**
The Dimensions handler element (among others) struggles with its backend configuration. If it is created for the first time, it does not offer the wanted configurational possibilities.

**To Reproduce**
1. In the backend, go to the Layouts tab and add the Dimensions handler element.
2. Edit the element and fill the blanks.
3. Notice that you cannot add a Dimensionsset with the "+"-button.
4. Save, close and reopen the dialogue to see the missing button.

**Expected behavior**
All configurational backend possibilities should be available from the initial creation of the element. 

**Versions**
 - Mapbender 3.0.8

**Screenshots**

![backend-no-dimensionset](https://user-images.githubusercontent.com/21199730/57608115-af54d180-756c-11e9-9b2e-f7c8bea56ded.png)

**Comment by astroidex** [comment] 2019-05-13 11:30
This is not a bug I guess. It is the same behaviour in element basesourceswitcher.

**Comment by rschwammborn** [comment] 2019-05-13 11:33
Switched issue to enhancement.

**Comment by werrolf** [comment] 2019-07-05 12:18
Fixed in v3.0.8.2.

**Closed by werrolf** 2019-07-05 12:18 UTC
Labels: Enhancement
