### ISSUE TITLE
openlayers6 - feature info point

### ISSUE THREAD

**Issue by beli2go** [mapbender/mapbender#1400] opened 2021-12-28 07:08 UTC
**Describe the bug**
If the Map Engine of a Application is set to OpenLayers6 then it will be impossible to get the feature information of a point feature displayed in the map.

**To Reproduce**
Switch the Map engine of a application to OpenLayers2(legacy).
Click a Point Feature in the Map to get FeatureInfo -> work.
Switch the Map engine to OpenLayers6.
Clicking the Point is nearly impossible. It works only if you have luck and get him exactly.

There is no search radius behind the click position

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.8

**Comment by rschwammborn** [comment] 2022-01-04 11:09
Hello @beli2go ,

tbh, I cannot reproduce this in Mapbender 3.2.8 - the point features I requested worked fine on both OL engines.

You could try the following while troubleshooting:

- Please check your layer configuration: Under Layersets, edit the concerning source and scroll down to check your requested layer. The checkbox "info allow" should be active (if it's grayed out without a checkmark, a feature info request on the layer is not supported by the source itself).
- You specified that it is "nearly impossible" to click a point feature - maybe even check your display resolution and if it is suiting your needs?

Hope that helps! I'm closing the issue as it doesn't seem to be a wider concern.

**Closed by rschwammborn** 2022-01-04 11:09 UTC
