### ISSUE TITLE
[frontend][redlining] Text is displayed with anchor point in map and print output.

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1126] opened 2019-03-22 10:48 UTC
**Describe the bug**
Text is displayed with anchor - in map and print output. Should not be like that. Was fine in Version 3.0.6.3 see https://version.mapbender3.org/3063/application/mapbender_user

**To Reproduce**
1. go to https://demo.mapbender.org/current/application/mapbender_user
2. Choose redlining in siedepane
3. Choose button text and define text
4. You will see the text in the map with a red circle 
5. in Version 3.0.6.3 the circle was not there. Which should be the normal behaviour. The circle could be displayed when you want to move the text.

**Expected behavior**
 in Version 3.0.6.3 the circle was not there. Which should be the normal behaviour. The circle could be displayed when you want to move the text to know how to grap the text.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta 3

**Screenshots / Logmessage**

**Additional context**

**Comment by werrolf** [comment] 2019-03-25 10:33
Duplicate of [#862](https://github.com/mapbender/mapbender/issues/862).

This is still intended. It allows you to seee what you labeled.

Same explanation as [#1134](https://github.com/mapbender/mapbender/issues/1134):  
You're describing behavior that was introduced in 1fd2c1725e6d000b94bef41cf6821b8f94ec10fc as part of PR #456, to resolve Issue #401, and first officially shipped in v3.0.5.4.

**Comment by astroidex** [comment] 2019-04-04 13:25
Maybe we should discuss what redlining is used for and how it should behave for a later version.

**Comment by eschuettler** [comment] 2019-06-26 08:48
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html

**Closed by eschuettler** 2019-06-26 08:48 UTC
Labels: Duplicate, Feature
