### ISSUE TITLE
Mapbender 3.0.6 performance on Windows and MS4W in particular

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#388] opened 2015-12-11 12:47 UTC
- with 3.0.5 we generate the css from the scss when we load an application
- this works fine on liux systems. But it causes performance problem on windows and make mapbender very slow in the backend and frontend
- urgent issue, should be fixed for 3.0.5.3

**Comment by AxxL** [comment] 2015-12-15 14:40
Unfortunetaly, this issue cannot be reproduced on every Windows installation but on a specific project. We took a deeper look into that and will optimize some caching mechanisms.

**Comment by AxxL** [comment] 2015-12-16 13:01
We made some improvements to css, js and trans so that they will be cached in app/cache. This is valid for the production environment (app.php). If you work in the development-environment (app_dev.php), they won't be cached.

This increases the performance for Linux and Windows. Please check, if this improvement works on your enviroment.

The commit takes place in the release/3.0.5 branch.

**Comment by jmckenna** [comment] 2016-05-25 17:42
I'm happy to finally discover this ticket.  MS4W (http://ms4w.com) distributes Mapbender as part of its installer on Windows.  Mapbender gets about 500 new installations on Windows each month through MS4W now.  Since we've been packaging Mapbender, I've noticed the slow load (1.5 minutes or more) on each test machine (Windows 10, Windows 7, Vista) for the CSS file (http://127.0.0.1/mapbender/application/manager/assets/css).  It can be reproduced on every test machine with the MS4W package.  I can't imagine how many possible Mapbender users are lost to this issue.

This is with Mapbender 3.0.5.3

Please let me know if you need help in testing this fix in the next release.  And distributing.

Thanks!

**Comment by jmckenna** [comment] 2016-05-25 17:46
I should also note that this occurs on every test Windows machine (my team's, plus the many reports from MS4W users - we get over 6,000 new installs a month now) with Mapbender's packaged demos.   This is obviously an urgent issue (as mentioned earlier in this ticket).   Should a new Mapbender release be cut for 3.0.5.4 with this fix, for the user community?

**Comment by jmckenna** [comment] 2016-05-25 17:54
If the answer is "this fix was supposed to be included in the 3.0.5.3 release" well then I am here telling you that it did not solve this issue, and this ticket should be reopened immediately.

**Comment by jmckenna** [comment] 2016-05-25 17:55
Please contact me if you need any testing with further fixes in regards to this issue on Windows.  Thanks.

**Comment by eSlider** [comment] 2016-05-30 08:09
Thank you @jmckenna! We will check CSS cache creation behaviour on Windows  and I will keep you in touch!

**Comment by gkvoelkl** [comment] 2016-08-24 13:01
I got the same issue on windows. It lasts about 10 second to get the first map. Is there a solution?

**Comment by jmckenna** [comment] 2017-01-31 13:21
I saw mention on the mailing list about this critical issue, but nothing is mentioned here in the ticket of an update, or a fix available.  Has there been any changes since 3.0.5.3 in regards to this issue?  If yes, please update this ticket.  Thanks!

**Comment by eSlider** [comment] 2017-02-17 10:23
There isn't problem of Mapbender3 or SASS Compiler. 
More about and how to fix it: http://stackoverflow.com/questions/9854848/windows-7-php-symfony2-terribly-slow

@astroidex, do we have description how to activate "opcache" and "wincache" on windows machine?

**Comment by AxxL** [comment] 2017-03-09 10:09
We have that documented in the Mapbender-documentation in the Windows-installation part.
http://doc.mapbender3.org/en/book/installation/installation_windows.html#optional-features

The solution will come with the next 3.0.6.0 version of mapbender and is right now part of the release/3.0.6 branch.

**Comment by eSlider** [comment] 2017-04-13 08:00
This is fixed outside of the mapbender in the SCSS library https://github.com/eSlider/sassc-binaries/commit/4777166f4d89ed23cf80a2b6b04759cb80da708f

**Comment by thokosch** [comment] 2017-05-05 06:23
Hello, But I'm experiencing the same problem on win10 64x. I installed wincache as suggested, cleared cache, but still - nothing changed. Do you have any working suggestions / experiences for windows users? Thanks and regards!

**Comment by AxxL** [comment] 2017-05-05 10:12
@thokosch 
> Do you have any working suggestions / experiences for windows users? 

It really depends on the system. We have some installations where we simply use PHP as an Apache module and we have systems where we use FCGID for integrating PHP with Apache. Seems to be related also with the Windows versions.

Coincidentally we updated the documentation yesterday with an example of FCGID in Apache (https://github.com/mapbender/mapbender-documentation/blob/release/3.0.6/de/book/installation/installation_windows.rst), since I had to create a new virtual machine for a small test.

So I integrated mod_fcgid, wincache and opcache and it works well and fast.

For opcache put the zend_extension=C:/bin/php/5.6.30/ext/php_opcache.dll line into php.ini.

**Comment by thokosch** [comment] 2017-05-06 14:44
Axel, thanks for the reply. I think I did everything as suggested but should mention that I use the latest MS4W installation where some paths are different but that should'nt be a problem (? e. g. zend_extension=C:/ms4w/Apache/php/ext/php_opcache.dll). I also saw there that FCGID is integrated and with geomoose for example everything works smoothly and fast right from start. But still - mapbender keeps slow. Isn't it possible to implement the nessesary accelaration(s) into MS4W? I guess that would attract lots of windows users.

**Comment by AxxL** [comment] 2017-05-11 10:19
@thokosch TBH I used in my projects the plain Apache Lounge Binaries, the Windows PHP stuff and all other things from the seperate installations. Coming from the Linux world it gives me a similar experience for customizations.

We had a customer the last days with MS4W and it looked rather OK. I need to take a deeper look into the MS4W stuff to give you an answer.

**Comment by jmckenna** [comment] 2017-05-11 12:18
please let me know as soon as possible if any changes to MS4W are needed for 3.0.6.0.  Mapbender is now getting around 1000 installs a month through MS4W, and I actually custom compile Apache by hand, along with PHP and its extensions, specifically for the Mapbender requirements.  You can file any changes needed directly into the MS4W tracker instance at http://ms4w.com/trac/   thank you.

**Comment by AxxL** [comment] 2017-05-11 16:20
@thokosch @jmckenna 

I have overwritten the mapbender3-3.0.5.0 with the MB3060 release zip to make it easy and made the following changes in php.ini:

``` diff
# diff php.ini php\ -\ Copy.ini 
450c450
< error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
---
> error_reporting = 22519 ;see values in http://ca2.php.net/manual/en/errorfunc.constants.php (all errors minus notices and deprecated)
573c573
< error_log = php_errors.log
---
> ;error_log = php_errors.log
901c901
< extension=php_mbstring.dll
---
> ;extension=php_mbstring.dll
940c940
< date.timezone = "Europe/Berlin"
---
> date.timezone = "UTC"
1908d1907
< zend_extension=C:/bin/php/5630/ext/php_opcache.dll
1910c1909
< opcache.enable=1
---
> ;opcache.enable=0
1916c1915
< opcache.memory_consumption=64
---
> ;opcache.memory_consumption=64
1919c1918
< opcache.interned_strings_buffer=4
---
> ;opcache.interned_strings_buffer=4
1923c1922
< opcache.max_accelerated_files=2000
---
> ;opcache.max_accelerated_files=2000
1926c1925
< opcache.max_wasted_percentage=5
---
> ;opcache.max_wasted_percentage=5
2037,2038d2035
< 
< wincache.reroute_enabled = 1
```

* The php_opcache.dll (C:/bin/php/5630/ext/php_opcache.dll) comes from my own PHP installation so I refered simply to it. It's a bit tricky to get that file from the archives at: https://www.iis.net/downloads/microsoft/wincache-extension

I add the zend_extension and the opcache.* Parameters.

* I added the php_mbstring.dll extension to php.

* I played with some params in the php.ini (timezone, logging, etc.)

**Comment by jmckenna** [comment] 2017-05-11 16:27
I compile by hand the mbstring extension for PHP, and MS4W loads it by default, so no need for users to go elsewhere to grab dlls (this is why MS4W is so popular, and why it is so reliable: you are bound to run into 'dll hell' once you start going elsewhere to download dlls and mixing sources on a Windows machine - this is the hard part for linux-based devs to understand.   Again, please feel free to file a ticket in MS4W tracker once you find any changes that are needed.  Thank you.

**Comment by jmckenna** [comment] 2017-05-11 16:29
i'll give it all a run-through again.  I am sure there are many customers out there waiting for MS4W to fix this issue (please have them contact me directly if they are stuck).  Thanks for the diff.

**Comment by AxxL** [comment] 2017-05-11 16:35
@jmckenna Jeff, with the DLL: I did a quick test for the wincache extension and haven't looked into ms4w if it's included. Therefore I simply referred to the DLL, I have placed in the former installation of PHP. If you wonder. ;)

Account for trac created.

**Comment by jmckenna** [comment] 2017-05-11 16:35
I also compile php_opcache.dll by hand in the same MS4W environment, and include this in the default MS4W.  Again, this avoids any potential 'dll hell'.   I will dive in again :)   k, sorry for all this noise.

**Comment by AxxL** [comment] 2017-05-11 16:36
@jmckenna No problem for that noise. (see this comment)

**Comment by jmckenna** [comment] 2017-05-11 16:37
good point about wincache, this is likely a new requirement for 3.0.6.0?  will take a look and include in MS4W if needed

**Comment by AxxL** [comment] 2017-05-11 16:38
@jmckenna I would include it.

**Comment by jmckenna** [comment] 2017-05-11 16:39
k will do.  I don't believe i compile that in by default.  that could be the difference :)

**Comment by AxxL** [comment] 2017-05-12 14:55
Since no commit is assigned to this issue I reopen it, change the title to a more specific one and put the milestone on 3.0.6.1. Otherwise it's hard to find the issue on the Issue-List.

**Comment by AxxL** [comment] 2017-05-12 16:08
I missed some of the params in the php.ini diff. Here is the list of relevant changes:

* max_execution_time = 150 (should help for starting first time)
* extension = php_wincache
* session.save_handler = wincache
* zend_extension=C:/bin/php/5630/ext/php_opcache.dll
* opcache.enable=1
* opcache.memory_consumption=64
* opcache.interned_strings_buffer=4
* opcache.max_accelerated_files=2000
* opcache.max_wasted_percentage=5

**Comment by thokosch** [comment] 2017-05-21 09:40
@jmckenna, @AxxL : can you preview when the ms4w will contain the performance changes to mapbender?

**Comment by jmckenna** [comment] 2017-05-21 14:57
@thokosch  please use this MS4W ticket to follow along (login there, click 'modify' ticket and add your username to the CC list, then you will be automatically notified of changes etc.):   http://ms4w.com/trac/ticket/63

**Comment by AxxL** [comment] 2017-05-23 16:39
I uploaded the changed httpd.conf from MS4W.

[httpd.conf.txt](https://github.com/mapbender/mapbender/files/1022918/httpd.conf.txt)

**Comment by jmckenna** [comment] 2017-07-13 15:16
Update: I spent much effort on this, and am very happy to let you know that I have compiled an MS4W release specifically with all of the changes needed for Mapbender 3.0.6.1......and it is working very fast!!!! MS4W 3.2.2 is available now at http://ms4w.com    It contains all of the extensions and changes needed for Mapbender including OPcache, PHP as FastCGI, etc.   MS4W is ready for FOSS4G-Europe!  💯

**Closed** 2017-07-14 10:12 UTC
Labels: WIP
