### ISSUE TITLE
Add button closes browser when editing application

### ISSUE THREAD

**Issue by kroesi** [mapbender/mapbender#1275] opened 2020-11-17 11:56 UTC
**Describe the bug**

The browser window closes when I try to add a button to the toolbar. 

Every time I click the "add" button in the "Add element" dialog, the browser window closes instead of the dialog.

I did some debugging and found that it happens here:

https://github.com/mapbender/mapbender/blob/f6717f050ab536f984ba0864e91c169b79032f01/src/Mapbender/ManagerBundle/Resources/public/js/application-edit.js#L214

```javascript
self.close(); // closes the browser window
```

**Version**
Mapbender 3.2.3

**Comment by LazerTiberius** [comment] 2020-11-17 13:58
Hi,
there is not version 3.2.3, do you mean 3.2.2? We can't reproduce your problem, can you give us some more information like the used browser, etc.

Cheers

**Comment by kroesi** [comment] 2020-11-17 14:29
I'm so sorry, I meant version 3.2.2  of course!

I've installed Mapbender under Windows:

- Apache 2.4 
- PHP 7.2
- Chrome Version 86.0.4240.183 (Offizieller Build) (32-Bit)

Click the "Add"-button:
![image](https://user-images.githubusercontent.com/19164607/99401799-e423b080-28e8-11eb-8f90-ea228714e25d.png)

self.close() is called:
![image](https://user-images.githubusercontent.com/19164607/99401985-20efa780-28e9-11eb-8e89-14039a77ab75.png)

Maybe I did something wrong during installation, but it has been a straightforward installation following your guidline under
https://doc.mapbender.org/de/installation/installation_windows.html

Many thanks for your efforts!

**Comment by thzanger** [comment] 2020-11-17 15:46
Hello @kroesi, I was unfortunately not able to recreate your issue. I tried using Chrome, Chromium and Firefox (Apache/2.4.41 
PHP 7.4.3). My advice would be to reinstall Mapbender and/ or check the settings of your browser. I will therefore close this issue. Regards

**Closed by thzanger** 2020-11-17 15:46 UTC
