### ISSUE TITLE
app/console mapbender:generate:element AdminType is missing after generation

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1033] opened 2018-10-05 07:52 UTC
**Describe the bug**
Mapbender provides a command to generate a new element. With Mapbender 3.0.7.x this command is not creating an element that can run with Mapbender, as the AdaminType is not generated and with the new Mapbender version AdminType seams to be mandatory. 

When you want to add the element to an application the error occurs: 

![mb_error](https://user-images.githubusercontent.com/996298/46522762-f286ed80-c883-11e8-9112-40b6bc633652.png)

https://github.com/mapbender/mapbender/issues/1023

The way to generate an element is described here:
https://doc.mapbender.org/en/development/element_generate.html
and referred from the DEVELOPER GUIDE https://github.com/mapbender/mapbender-starter/blob/master/CONTRIBUTING.md

**What to discuss**
We have to discuss, whether we want to update the command or set is to deprecated and delete the how-to and link in the developer Guide. 
Question: Is it usefull? Or is it not used anyway.

**To Reproduce**
1. create the new element
2. add it to an application
3. error message occurs

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.3

**Screenshots / Logmessage**
![mb_error](https://user-images.githubusercontent.com/996298/46522762-f286ed80-c883-11e8-9112-40b6bc633652.png)

**Comment by werrolf** [comment] 2019-01-18 15:35
Duplicate of #1023.

**Closed by werrolf** 2019-01-18 15:35 UTC
Labels: Bug
