### ISSUE TITLE
[featureInfo] dialog sometimes does not show all tabs

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#939] opened 2018-06-20 12:12 UTC
* when you get results from many WMS on featureinfo some result tabs are hidden
* internal ticket 51

Hochwasser is only shown twice although it is 3 times loaded in the application
![mb_bug_featureinfo_tab](https://user-images.githubusercontent.com/996298/41657495-d2d08544-7493-11e8-81ee-487343f1cfe9.PNG)

Steps to reproduce

1. Open an application f.e. https://demo.mapbender.org/application/mapbender_user
2. Load WMS  several times into the application http://www.wms.nrw.de/umwelt/HW_Gefahrenkarte?&VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS
3. Hit featureInfo 
4. Count the result tabs in the dialog that opens

**Comment by werrolf** [comment] 2019-01-18 12:01
The tab is there. The issue is that the tab container CSS used in feature info fails to force all tabs onto a horizontal order. Which isn't necessarily what you want, because you would have to scroll horizontally to see the tabs.

The feature info dialog is resizable. If you make it wider, all your tabs come back.

I'm not sure what solution you expect.

**Comment by rschwammborn** [comment] 2019-05-06 07:58
I don't see a real bug/issue here. In Mapbender 3.0.8, the tabs are not hidden anymore. Instead, CSS arranges them vertically (as long as the feature dialog is small), which is fine to me. Therefore, I'm closing the issue.

**Closed by rschwammborn** 2019-05-06 07:58 UTC
Labels: Bug
