### ISSUE TITLE
Click interaction

### ISSUE THREAD

**Issue by alissonrodrigo** [mapbender/mapbender#1555] opened 2024-03-04 20:39 UTC
I didn't find in the documentation and I didn't find forums about mapbender how I can add map interaction with the user via click, where it can open a second created map or just a window with information about the clicked point. Thank you very much

**Comment by Phocacius** [comment] 2024-05-28 12:49
Hi @alissonrodrigo,
thank you for your question and sorry for the late response.

To add a custom interaction you need to create a custom element. A better development documentation is currently being created, you can already have a look at the draft version of how to create your own element here: https://github.com/mapbender/mapbender/blob/docs/devdocs/docs/elements/elements.md
You can also have a look at an existing element on how it's done there, e.g. for the feature info element https://github.com/mapbender/mapbender/blob/develop/src/Mapbender/CoreBundle/Resources/public/mapbender.element.featureInfo.js#L388

If you need further help, feel free to answer to this issue, I'll still close it since it's not a bug or feature request that needs to be addressed in the future.

**Closed by Phocacius** 2024-05-28 12:49 UTC
Labels: Question
